spring:
  application:
    name: wangxz-blog
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:2222/

server:
  port: 3333



#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:1111/eureka/
#  instance:
#    prefer-ip-address: true #注册时使用ip地址