spring:
  application:
    name: gateway-server
#  cloud:
#    Oauth2Config:
#      profile: dev
#      discovery:
#        enabled: true
#        service-id: Oauth2Config-server
#      label: master


server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true #注册时使用ip地址