server:
  port: 3333

spring:
  application:
    name: gateway-server
  # thymeleaf start
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    # 开发时关闭缓存
    cache: false
  # thymeleaf end
#  cloud:
#    Oauth2Config:
#      profile: dev
#      discovery:
#        enabled: true
#        service-id: Oauth2Config-server
#      label: master

# 配置网关设置
zuul:
  # 转发规则
  routes:
    # admin-server配置context
    admin-server:
      # 该属性决定了转发头部（黑名单制）
      sensitiveHeaders:
      path: /admin/**
      stripPrefix: false
    security-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
  # 是否添加proxy头部，可以用于验证
  add-proxy-headers: true

security:
  # 关闭默认的basic验证
  basic:
    enabled: false
  # oauth2验证相关
  oauth2:
    sso:
      # 登陆地址
      loginPath: /login
    # 客户端信息
    client:
      accessTokenUri: http://security-service/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    # jwt配置
    resource:
      jwt:
        # TODO: 公钥分离到文件
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

# Eureka
eureka:
  instance:
    hostname: localhost
    port: 1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
